--liquibase formatted sql
--changeset emad:1

CREATE TABLE TEMPLATE_BASE_ENTITY
(
    ID                UUID PRIMARY KEY,
    CREATION_DATE     TIMESTAMPTZ,
    MODIFICATION_DATE TIMESTAMPTZ
);


CREATE TABLE EMAIL_TEMPLATES
(
    ID           UUID UNIQUE,
    NAME         VARCHAR(200),
    DESCRIPTION  VARCHAR(500),
    IS_GLOBAL    BOOLEAN DEFAULT TRUE,
    TYPE         VARCHAR(50),
    IS_PUBLISHED BOOLEAN DEFAULT FALSE,
    SUBJECT      TEXT,
    BODY         TEXT,
    LANGUAGE     VARCHAR(20),
    CONSTRAINT FK_EMAIL_TEMPLATES FOREIGN KEY (ID)
        REFERENCES TEMPLATE_BASE_ENTITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE URL_TEMPLATES
(
    ID           UUID UNIQUE,
    NAME         VARCHAR(200),
    DESCRIPTION  VARCHAR(500),
    IS_GLOBAL    BOOLEAN DEFAULT TRUE,
    TYPE         VARCHAR(50),
    IS_PUBLISHED BOOLEAN DEFAULT FALSE,
    URL          TEXT,
    LANGUAGE     VARCHAR(20),
    CONSTRAINT FK_URL_TEMPLATES FOREIGN KEY (ID)
        REFERENCES TEMPLATE_BASE_ENTITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE QUICK_TEXT_TEMPLATES
(
    ID           UUID UNIQUE,
    NAME         VARCHAR(200),
    DESCRIPTION  VARCHAR(500),
    IS_GLOBAL    BOOLEAN DEFAULT TRUE,
    TYPE         VARCHAR(50),
    IS_PUBLISHED BOOLEAN DEFAULT FALSE,
    TEXT_RESPONSE         TEXT,
    LANGUAGE     VARCHAR(20),
    CONSTRAINT FK_QUICK_TEXT_TEMPLATES FOREIGN KEY (ID)
        REFERENCES TEMPLATE_BASE_ENTITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE ATTACHMENTS
(
    ID                UUID PRIMARY KEY,
    MEDIA_ID          VARCHAR(50),
    TYPE              VARCHAR(50),
    NAME              VARCHAR(50),
    URL               VARCHAR(500),
    EMAIL_TEMPLATE_ID UUID
        CONSTRAINT FK_ATTACHMENTS_TEMPLATES
            REFERENCES EMAIL_TEMPLATES (ID)
);

CREATE TABLE ATTRIBUTES
(
    ID          UUID PRIMARY KEY,
    VALUES      JSONB        NOT NULL,
    CATEGORY    VARCHAR(255) NOT NULL,
    PRIORITY    INTEGER,
    TEMPLATE_ID UUID,
    CONSTRAINT FK_ATTRIBUTES_TEMPLATES FOREIGN KEY (TEMPLATE_ID)
        REFERENCES TEMPLATE_BASE_ENTITY (ID) MATCH SIMPLE
        ON UPDATE NO ACTION ON DELETE CASCADE
);

CREATE TABLE ATTRIBUTE_TEMPLATES
(
    ATTRIBUTE_ID UUID REFERENCES ATTRIBUTES (ID) ON DELETE CASCADE,
    TEMPLATE_ID  UUID REFERENCES TEMPLATE_BASE_ENTITY (ID) ON DELETE CASCADE,
    ID           BIGSERIAL PRIMARY KEY
);